#   _      ____  _     _____ ____    ____  _     ____  ____  ____  _  _      _____
#  / \  /|/  _ \/ \ |\/  __//  __\  / ___\/ \ /|/  _ \/  __\/  __\/ \/ \  /|/  __/
#  | |\ ||| / \|| | //|  \  |  \/|  |    \| |_||| / \||  \/||  \/|| || |\ ||| |  _
#  | | \||| |-||| \// |  /_ |    /  \___ || | ||| \_/||  __/|  __/| || | \||| |_//
#  \_/  \|\_/ \|\__/  \____\\_/\_\  \____/\_/ \|\____/\_/   \_/   \_/\_/  \|\____\

# Title of your website
title: 'SHOWROOM::네이버쇼핑'
# The slogan describes your website and is used on homepage in <title> and other important places
slogan: '쇼핑 개발자를 부탁해'
# The description is used on homepage and in the footer to quickly describe your website. Use a maximum of 150 characters for SEO-purposes.
description: '»네이버 쇼핑 개발자들의 놀이터. 개발하며 겪은 경험을 공유하고 새로운 기술을 소개합니다. '
# The credits show up in the includes/_footer.html – It would be nice of you to leave a link to Phlow or Feeling Responsive as a thank you :)
credits: '<p>Created with &hearts; by <a href="https://shopping.naver.com/">NAVER SHOPPING</a>'
# Main author of the website
author: shopping
# This URL is the main address for absolute links. Don't include a slash at the end.
url: 'https://nshop-developer.github.io'
baseurl: ''

# This is for the editing function in _/includes/improve_content
# Leave it empty if your site is not on GitHub/GitHub Pages
improve_content: https://github.com/nshop-developer/nshop-developer.github.io/settings/gh-pages

# This URL points directly to the images directory making
# things easier to link to images in posts and templates. It needs a slash at the end.
#
# Example: <img src="{{ site.urlimg }}{{ post.image.title }}" />
# Markdown-Example for posts ![Image Text]({{ site.urlimg }}image.jpg)
#
urlimg: 'http://nshop-developer.github.io/images/'

# Logo size is 600x80 pixels
logo: "logo.png"

# Plugins
plugins:
    - jekyll-asciidoc
    - jekyll-gist
    - jekyll-paginate

paginate: 5                      # Paginates all X entries
paginate_path: "blog/page:num"   # Pagination path › Important for blog page in /blog/ to work

# Theme works best with Kramdown (using the table of contents function)
markdown           : kramdown
#permalink          : /:categories/:title/
permalink          : /:year/:month/:day/:title/
highlight          : rouge
excerpt_separator  : "<!--more-->"
include            : ['.htaccess']
# Exclude these files from your production _site
exclude:
    - .sass-cache
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - INSTALL.md
    - vendor

language: 'ko-KR"'
# Used › default.html front-matter and compress.html
# Options › http://jch.penibelst.de
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false
  ignore:
    envs: [development]

defaults:
  -
    scope:
      path: '' 				# an empty string here means all files in the project
      type: 'pages'
    values:
      show_meta: false 	# Hide metadata for all pages
      # sidebar:    		# Possible values › left, right › by default there will be no sidebar
      comments: false
      author: shopping     # Default author for pages
  -
    scope:
      path: ''
      type: 'posts'
    values:
      show_meta: true   # Show metadata for all posts
      # sidebar:        # Possible values › left, right › by default there will be no sidebar
      comments: false
      author: shopping     # Default author for posts



#       _   __            _             __  _
#      / | / /___ __   __(_)___ _____ _/ /_(_)___  ____
#     /  |/ / __ `/ | / / / __ `/ __ `/ __/ / __ \/ __ \
#    / /|  / /_/ /| |/ / / /_/ / /_/ / /_/ / /_/ / / / /
#   /_/ |_/\__,_/ |___/_/\__, /\__,_/\__/_/\____/_/ /_/
#                       /____/
#
#  Open _data/navigation.yml to adjust the left and right topbar navigation
#



#     _____ __________
#    / ___// ____/ __ \
#    \__ \/ __/ / / / /
#   ___/ / /___/ /_/ /
#  /____/_____/\____/    Verify Website to Webmaster Tools

google_site_verification:  '5RFjA9KTgQLVprur2qSYPIfMtAuRu-Y-Ddq5fSsU62g'
# yandex_site_verification:  ''
# alexa_verify_id:           ''
#       ______            _
#      / ____/___ __   __(_)________  ____  _____
#     / /_  / __ `/ | / / / ___/ __ \/ __ \/ ___/
#    / __/ / /_/ /| |/ / / /__/ /_/ / / / (__  )
#   /_/    \__,_/ |___/_/\___/\____/_/ /_/____/   Favicon-Crap: Favicons, Chrome, Android & Apple Touch Buttons
#                                                 More information » https://mathiasbynens.be/notes/touch-icons

favicon-32x32:                          'favicon-32x32.png'
touch-icon-192x192:                     'touch-icon-192x192.png'
apple-touch-icon-180x180-precomposed:   'apple-touch-icon-180x180-precomposed.png'
apple-touch-icon-152x152-precomposed:   'apple-touch-icon-152x152-precomposed.png'
apple-touch-icon-144x144-precomposed:   'apple-touch-icon-144x144-precomposed.png'
apple-touch-icon-120x120-precomposed:   'apple-touch-icon-120x120-precomposed.png'
apple-touch-icon-114x114-precomposed:   'apple-touch-icon-114x114-precomposed.png'
apple-touch-icon-76x76-precomposed:     'apple-touch-icon-76x76-precomposed.png'
apple-touch-icon-72x72-precomposed:     'apple-touch-icon-72x72-precomposed.png'
apple-touch-icon-precomposed:           'apple-touch-icon-precomposed.png'
msapplication_tileimage:                'msapplication_tileimage.png'               # Size 144x144
msapplication_tilecolor:                '#fabb00'

og_image:                           'https://ssl.pstatic.net/imgshopping/cnsv/m/im/ogtag/01_nshopping.png'
og_locale:                          'ko_KR'
og_type:                            'website'

socialmedia:
  twitter:
  facebook:


disqus_shortname: nshop-developer

sass:
    sass_dir : _sass
    style    : :compressed


google_analytics_tracking_id: UA-148955016-1

#   _                 _     _
#  | |_ __ ___      _| | __| |_ ___
#  | __/ _` \ \ /\ / / |/ /| __/ _ \
#  | || (_| |\ V  V /|   < | || (_) |
#   \__\__,_| \_/\_/ |_|\_(_)__\___/     More › https://www.tawk.to/knowledgebase/
#
#  tawk.to is a free live chat app that lets you monitor and chat
#  with visitors on your website or from a free customizable page
#
#  To load the script add tawkto: true in front matter of each page
#
# used in _includes/footer_scripts

# tawkto_embed_uri:


#     ___              _     __           __
#    /   |  __________(_)___/ /___  _____/ /_____  _____
#   / /| | / ___/ ___/ / __  / __ \/ ___/ __/ __ \/ ___/
#  / ___ |(__  ) /__/ / /_/ / /_/ / /__/ /_/ /_/ / /
# /_/  |_/____/\___/_/\__,_/\____/\___/\__/\____/_/
#
#  Asciidoctor is a fast text processor and publishing toolchain for converting
#  AsciiDoc content to HTML5, DocBook 5 (or 4.5) and other formats.
#
#  https://github.com/asciidoctor/jekyll-asciidoc
#  https://github.com/asciidoctor
#
#

asciidoctor-enabled: false
asciidoctor:
  description: testtewtetrue
  attributes:
    source-highlighter: coderay
    coderay-css: style
    icons: font
